Add date filters
burnNturn/edenvr-survey pull request #12
Opened 2017-05-07 01:30 UTC by burnNturn

I added date pickers to filter the date also.  Everything works great with the server and database logic, but I couldn't get the "end_date" datepicker to default to today (tried using jquery, seems like it should be working), I think I have a way around this, but it seems a little sloppy.  

I also wanted to use jquery(?) to only render the table after a filter, which it is doing, but something is going wrong in my logic, it seems to be using @customers.all to fill the table (before I added the jquery it was filtering by date correctly, so it isn't that).

Just a heads up, I have two byebugs in there right now (one in customers_controller.index and one in the customers model) and I have a debugger in my index.js.erb.

Can you take a look at these, and see what I am doing wrong, or at least lead me into the right direction?

2017-05-07 20:06 UTC, Jabronious requested changes

2017-05-07 20:06 UTC, Jabronious commented on app/controllers/customers_controller.rb
> +        format.html
do you need the format.html?

2017-05-07 20:06 UTC, Jabronious commented on app/views/customers/index.html.erb
> +          $( "#start_date" ).datepicker();
you should be able to do ("#start_date, #end_date").datepicker();

2017-05-07 20:06 UTC, Jabronious commented on app/views/customers/index.html.erb
> +          $( "#start_date" ).datepicker();
Also, inside .datepicker([PUT_DEFAULT_STUFF]); ... check documentation on what you can put in there though not 100% sure names and such

2017-05-07 23:29 UTC, burnNturn commented on app/controllers/customers_controller.rb
> +        format.html
Seems that I do, I believe that when the page initially loads, it is an html request.  I get an "UnknownFormat" error on the initial page load if I remove it.

2017-05-08 01:10 UTC, burnNturn commented
All issues resolved.

2017-05-08 01:10 UTC, merged